### ISSUE TITLE
Apache License?

### ISSUE THREAD

**Issue by Sprocketer** [fsmosca/sample-streamlit-authenticator#2]
Cool we had the same exact idea for this repo by chance haha

Anyways how come you use an apache license? It means anyone using this would have to put a notice in every modified file that they modified it - super inconvenient

Also the license isn't valid (yet) because you haven't filled in the square brackets at the bottom with your name and the year this was created (2024 obviously)

Also you should convert this into a template repository - go to (repository) Settings -> General

**Comment by Sprocketer** [comment]
If you really want to give free distribution and modification rights use Unlicense (if that's your goal)

**Comment by fsmosca** [comment]
The reason why it is like that is because streamlit is apache and streamlit-authenticator is apache too.

**Comment by fsmosca** [comment]
This repo is now a template.
